name = "ncepuwiki-image-uploader"
main = "src/index.ts"
compatibility_date = "2026-09-08"

[vars]
IMAGE_BASE_URL = "https://img.ncepuinfo.cc"
REQUIRE_AUTH = "true"
ADMIN_EMAILS = "1361942776@qq.com,2668566027@qq.com"
# Cloudflare Access 登录团队域名与 Application Audience（用于校验 JWT 签名）
ACCESS_TEAM_DOMAIN = "https://ncepuwiki.cloudflareaccess.com"
ACCESS_AUD = "611b1c0247488b8e43511c4067980306c89afd3a8305769957e37f2fcbb9daaa"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "ncepuwiki-image"
preview_bucket_name = "ncepuwiki-image"
